name: Stormfront
version: '${version}'

main: com.eande171.stormfront.PluginMain
api-version: '1.21'
load: POSTWORLD

description: Dynamic weather plugin for Paper servers
authors: [ Eden Anderson ]

depend: [ StormfrontAPI, packetevents ]

permissions:
  stormfront.admin:
    description: Allows use of all Stormfront commands
    default: op
