name: StormfrontAPI
version: '${version}'

main: com.eande171.stormfront.api.StormfrontApiPlugin
api-version: '1.21'
load: POSTWORLD

depend: [ packetevents ]

description: Stormfront API - engine and dependency for Stormfront weather packs and add-ons
authors: [ Eden Anderson ]


permissions:
  stormfront.admin:
    description: Allows use of all Stormfront commands
    default: op
